feat: add incremental caching
martinothamar/Mediator pull request #113
Opened 2023-09-22 22:42 UTC by TimothyMakkison

Modify `CompilationAnalyzer` to return an equitable model skipping the final build and emit stage

2023-11-02 06:41 UTC, martinothamar commented
Awesome work! In my experimental branch I think I removed the Roslyn38 project, was trying to simplify. Do you know what version of the SDK is needed for 4.1?

2023-12-07 22:39 UTC, martinothamar requested changes
Thanks for your patience, sorry about the delay here!

A couple of comments, otherwise this looks awesome :1st_place_medal: 
I must admit I don't understand all these Roslyn APIs related to incremental compilation, but you bring benchmarks (which I ran) and tests so LGTM :smile: 


``` ini

BenchmarkDotNet=v0.13.1, OS=pop 22.04
AMD Ryzen 5 5600X, 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.417
  [Host] : .NET 6.0.25 (6.0.2523.51912), X64 RyuJIT

Job=InProcess  Toolchain=InProcessEmitToolchain  

```
|       Method |      Mean |    Error |   StdDev |    Gen 0 |    Gen 1 | Allocated |
|------------- |----------:|---------:|---------:|---------:|---------:|----------:|
|       Cached |  13.69 ms | 0.053 ms | 0.047 ms | 265.6250 |  78.1250 |     22 MB |
|      Compile |  14.89 ms | 0.056 ms | 0.049 ms | 265.6250 | 265.6250 |     23 MB |
|  LargeCached |  87.59 ms | 0.327 ms | 0.290 ms | 333.3333 | 166.6667 |     38 MB |
| LargeCompile | 154.20 ms | 0.807 ms | 0.755 ms | 750.0000 | 250.0000 |     77 MB |

2023-12-07 22:39 UTC, martinothamar commented on src/Mediator.SourceGenerator.Implementation/Analysis/CompilationAnalyzer.cs
> +            report.ReportGenericError(ex);
I don't quite understand the changes here together with `_diagnostics` and `ReportDiagnostic`. Don't these diagnostic just end up getting dropped on the floor, since they're not sent to the context?

2023-12-07 22:39 UTC, martinothamar commented on src/Mediator.SourceGenerator.Implementation/Analysis/RequestMessageHandlerWrapper.cs
> -        _analyzer = analyzer;
I think this change breaks cases where the namespace is configured by the user. `TryParseConfiguration` is the last step of analysis for some reason, at which point `MediatorNamespace` as already been captured here. We could move up `TryParseConfiguration`, maybe that's cleaner. What do you think?

2023-12-07 22:39 UTC, martinothamar commented on src/Mediator.SourceGenerator.Implementation/Models/RequestMessageHandlerWrapperModel.cs
> +    public void WeirdBug() => throw new Exception();
This must have an interesting origin story :smile:

2023-12-07 23:29 UTC, TimothyMakkison commented
Thanks for the review, I'll resolve the issues when I have more time over the weekend 👍 

> I must admit I don't understand all these Roslyn APIs related to incremental compilation

TLDR, each step in a incremental generator (`Select`, `Where`, `SelectMany`), caches the input and output of the previous runs step. By using a custom comparer or object implementing `IEquality` we can use this behaviour to skip a section of the pipeline if the input object is the same as the last run.

In roslyn equivalent syntax (ie `SyntaxNode`, `InvocationExpressionSyntax`) is the same between runs whereas each compilation object will always be different between runs (`ITypeSymbol`, `ISymbol`, `Compilation`) and should not be cached for both performance and logic reasons. 

In our case I created a parse step that produces a cacheable object, this lets us skip the output stage.

2023-12-07 23:32 UTC, martinothamar commented
Thanks! Makes sense

2023-12-07 23:34 UTC, TimothyMakkison commented on src/Mediator.SourceGenerator.Implementation/Models/RequestMessageHandlerWrapperModel.cs
> +    public void WeirdBug() => throw new Exception();
I'm not allowed to delete this file, I have no idea why not...

![image](https://github.com/martinothamar/Mediator/assets/49349513/c55b014c-e714-4517-a72b-9ea80d61bea8)

2023-12-12 08:47 UTC, TimothyMakkison commented on src/Mediator.SourceGenerator.Implementation/Models/RequestMessageHandlerWrapperModel.cs
> +    public void WeirdBug() => throw new Exception();
I was able to delete this but I'm not able to update`RequestMessageHandlerWrapper.cs` to this filename. I have no idea what voodoo caused this.

2023-12-30 16:20 UTC, TimothyMakkison commented on src/Mediator.SourceGenerator.Implementation/Analysis/RequestMessageHandlerWrapper.cs
> -        _analyzer = analyzer;
Not sure either. Rereading the code I'm wondering if using the immutable models in the mutable code is a good idea as it makes mistakes like this common.

2023-12-31 17:02 UTC, TimothyMakkison commented on src/Mediator.SourceGenerator.Implementation/Analysis/CompilationAnalyzer.cs
> +            report.ReportGenericError(ex);
Good catch, suprised a unit test didn't catch this.

2024-01-01 21:00 UTC, TimothyMakkison commented
Thanks for the review, I think I've made all the relevant changes 👍 

- I opted to use your approach and moved `TryParseConfiguration` to before the array declaration
- `RequestMessageHandlerWrapper` is still a little janky. My ide doesn't show linting if the file is in the `Models` folder, but will lint and show references when moved out. Still no idea why this is happening. It occurs on different computers with fresh installs 😩
- I'm a little conversned that the tests didn't fail when I broke diagnostics or namespace configuration. I'm planning on adding some tests to `SnapshotTests`. Should I add them in this pr or a different one? This pr is getting a little bloated.

2024-02-20 17:39 UTC, martinothamar approved these changes
finally merging this, thanks for the great work! :smile:

2024-02-20 17:39 UTC, merged