Run notification handlers in parallel
martinothamar/Mediator pull request #116
Opened 2023-10-17 13:32 UTC by Neo-vortex

run notifications handlers in parallel
closes https://github.com/martinothamar/Mediator/issues/115

2023-10-23 22:29 UTC, TimothyMakkison requested changes

2023-10-23 22:29 UTC, TimothyMakkison commented on src/Mediator.SourceGenerator.Implementation/resources/Mediator.sbn-cs
> +                                            var tasks = handlers.Select(handler =>  handler.Handle(notification, cancellationToken).AsTask()).ToArray();
Is `AsTask` needed? I think this cause a `Task` to be allocated. Perhaps `ConfigureAwait(false)` could be used instead.

2023-10-23 22:29 UTC, TimothyMakkison commented on src/Mediator.SourceGenerator.Implementation/resources/Mediator.sbn-cs
> +                                          {
Broken indentation.

2023-10-24 06:54 UTC, martinothamar requested changes
Thanks for the PR!

To make this viable we need to make publishing strategy configurable, so that not all users pay the perf cost (allocations). We should look into the MediatR implementation for inpiration. Generally I try to adopt the same APIs as MediatR unless there is a large enough tradeoff made in terms of perf vs ergonomics. Maybe you can make an API proposal first in #115 ?

2023-10-24 08:04 UTC, Neo-vortex commented on src/Mediator.SourceGenerator.Implementation/resources/Mediator.sbn-cs
> +                                            var tasks = handlers.Select(handler =>  handler.Handle(notification, cancellationToken).AsTask()).ToArray();
I think so,
because `Task.WhenAll()` does not support value tasks

2023-10-24 10:35 UTC, TimothyMakkison commented on src/Mediator.SourceGenerator.Implementation/resources/Mediator.sbn-cs
> +                                            var tasks = handlers.Select(handler =>  handler.Handle(notification, cancellationToken).AsTask()).ToArray();
See my [comment](https://github.com/martinothamar/Mediator/issues/115#issuecomment-1776921370) for a possible alternative.

2023-11-04 15:01 UTC, TimothyMakkison commented on src/Mediator.SourceGenerator.Implementation/resources/Mediator.sbn-cs
> +                                            var tasks = handlers.Select(handler =>  handler.Handle(notification, cancellationToken).AsTask()).ToArray();
Unnecessary `ToArray` call, `Task.WhenAll` always creates a defensive array copy.

2024-04-07 08:59 UTC, martinothamar commented
Superseded by #145

2024-04-07 08:59 UTC, closed without merging